# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPxXnefETv89-DaR4La1ufYPGVdJCAjB
"""

# Commented out IPython magic to ensure Python compatibility.
%pip install streamlit

#from google.colab import drive
#drive.mount('/content/drive')


import streamlit as st
import pandas as pd

# Load data
df = pd.read_csv("/workspaces/e-commerce-analytics-dashboard/data/cleaned_dataset.csv", parse_dates=["order_date"])

st.title("📊 E-Commerce Analytics Dashboard")

# Sales over time
st.header("Sales Over Time")
monthly_sales = df.groupby(df["order_date"].dt.to_period("M"))["sales_value"].sum()
st.line_chart(monthly_sales)

# Top products
st.header("Top 10 Products")
top_products = df.groupby("product_id")["sales_value"].sum().sort_values(ascending=False).head(10)
st.bar_chart(top_products)

# Sales by category
st.header("Sales by Category")
category_sales = df.groupby("category")["sales_value"].sum()
st.bar_chart(category_sales)

# Customer segmentation
st.header("Sales by Age Group")
bins = [18,25,35,45,55,65]
labels = ["18-24","25-34","35-44","45-54","55-64"]
df["age_group"] = pd.cut(df["age"], bins=bins, labels=labels, right=False)
age_sales = df.groupby("age_group")["sales_value"].sum()
st.bar_chart(age_sales)
